var excel = new ActiveXObject("Excel.Application"); // 创建AX对象excel
excel.visible = true; // 设置excel可见属性
var workbook = excel.Workbooks.Add; // 获取workbook对象
var sheet1 = xlBook.Worksheets(2); // 创建sheet1
var sheet2 = xlBook.Worksheets(1); // 创建sheet2
sheet1.Range(sheet1.Cells(1, 1), sheet1.Cells(1, 14)).mergecells = true; // 合并单元格
sheet1.Range(sheet1.Cells(1, 1), sheet1.Cells(1, 14)).value = "员工月考核成绩"; // 设置单元格内容
sheet1.Range(sheet1.Cells(1, 1), sheet1.Cells(1, 14)).Interior.ColorIndex = 6;// 设置底色
sheet1.Range(sheet1.Cells(1, 1), sheet1.Cells(1, 14)).Font.ColorIndex = 5;// 设置字体色
sheet1.Rows(1).RowHeight = 20; // 设置列高
sheet1.Rows(1).Font.Size = 16; // 设置文字大小
sheet1.Rows(1).Font.Name = "宋体"; // 设置字体
// 设置每一列的标题
sheet1.Cells(2, 1).Value = "工程师考核项";
sheet1.Cells(2, 2).Value = "总分";
sheet1.Cells(2, 3).Value = "研发进度";
sheet1.Cells(2, 4).Value = "出勤率";
sheet1.Cells(2, 5).Value = "执行力";
sheet1.Cells(2, 6).Value = "责任心";
sheet1.Cells(2, 7).Value = "工作规范";
sheet1.Cells(2, 8).Value = "协作精神";
sheet1.Cells(2, 9).Value = "进取性";
sheet1.Cells(2, 10).Value = "工作合理性";
sheet1.Cells(2, 11).Value = "解决问题能力";
sheet1.Cells(2, 12).Value = "应变能力";
sheet1.Cells(2, 13).Value = "人际技能";
sheet1.Cells(2, 14).Value = "理解能力";
// 从表单循环控件中取出数据逐行插入对应列的数据
var count = sfform.GetAttributeValue('Repeat', 'Count');
for ( var line = 1; line <= count; line++) { // begin for
	var name = sfform.GetValue('Repeat[' + line + '].name');
	var total = sfform.GetValue('Repeat[' + line + '].total');
	var yfjd = sfform.GetValue('Repeat[' + line + '].yfjd');
	var jh = sfform.GetValue('Repeat[' + line + '].jh');
	var gcgj = sfform.GetValue('Repeat[' + line + '].gcgj');
	var cql = sfform.GetValue('Repeat[' + line + '].cql');
	var zxl = sfform.GetValue('Repeat[' + line + '].zxl');
	var gzgf = sfform.GetValue('Repeat[' + line + '].gzgf');
	var zrx = sfform.GetValue('Repeat[' + line + '].zrx');
	var xzjs = sfform.GetValue('Repeat[' + line + '].xzjs');
	var jqx = sfform.GetValue('Repeat[' + line + '].jqx');
	var gzhl = sfform.GetValue('Repeat[' + line + '].gzh');
	var jjwt = sfform.GetValue('Repeat[' + line + '].jjwt');
	var ybnl = sfform.GetValue('Repeat[' + line + '].ybnl');
	var rjjn = sfform.GetValue('Repeat[' + line + '].rjjn');
	var ljnl = sfform.GetValue('Repeat[' + line + '].ljnl');
	sheet1.Cells(2 + line, 1).Value = name;
	sheet1.Cells(2 + line, 2).Value = total;
	sheet1.Cells(2 + line, 3).Value = yfjd;
	sheet1.Cells(2 + line, 4).Value = cql;
	sheet1.Cells(2 + line, 5).Value = zxl;
	sheet1.Cells(2 + line, 6).Value = gzgf;
	sheet1.Cells(2 + line, 7).Value = zrx;
	sheet1.Cells(2 + line, 8).Value = xzjs;
	sheet1.Cells(2 + line, 9).Value = jqx;
	sheet1.Cells(2 + line, 10).Value = gzhl;
	sheet1.Cells(2 + line, 11).Value = jjwt;
	sheet1.Cells(2 + line, 12).Value = ybnl;
	sheet1.Cells(2 + line, 13).Value = rjjn;
	sheet1.Cells(2 + line, 14).Value = ljnl;

}// end for
