#!/bin/bash

# export JAVA_HOME=/usr/java/j2sdk1.4.1
export LC_ALL="en_US.UTF-8"
export JAVA_HOME=/usr/java/j2sdk
export TOMCAT_HOME=/home/zlei/apache-tomcat-5.5.30
# for fop Chinese fonts, must increase the JVM memory heep size
# JasperReport requires headless option
#export JAVA_OPTS="-Xms1024m -Xmx2048m -Djava.awt.headless=true -Dfile.encoding=UTF-8" 

startup=$TOMCAT_HOME/bin/startup.sh
shutdown=$TOMCAT_HOME/bin/shutdown.sh

$shutdown
sleep 10

psout=`ps -ef|grep java|grep xpc|grep -v grep|awk '{print $2}'`
if [ -n $psout ]; then
   for pid in $psout
   do
       kill -9 $pid
   done
fi

$startup
